### ISSUE TITLE
Expose ContainerDefinitions.command

### ISSUE THREAD

**Issue by ambsw-technology** [cfn-modules/fargate-service#17]
We have a bunch of situations where we run multiple container based on the same image.  For example:

 - We need to run a `migrate` command on our app containers to do the database migration
 - Python's Celery package requires asynchronous workers that share the same code base as the application.
 - Our messaging system polls several API endpoints.  99% of the code is common so we run different services (API endpoint, message recipient) out of the same container.

The right way to do this is almost certainly to use a different `command` for each container.  Fortunately, most of our services are selected (within supervisor) using environment variables so our need is not urgent.  However, I wanted to share the requirement for your consideration.

**Comment by michaelwittig** [comment]
Hi! A few questions to clarify your requirements:

The migrate should only run once? A ECS service is designed to keep something running forever. As soon as the container exists, a new one is created which performs the migration again and again. A simple ECS task might be a better fit? Like https://github.com/cfn-modules/fargate-scheduled-task but without the scheduler?

Can you show me the different "Celery" commands to run the application versus the workers?

Thanks!

**Comment by ambsw-technology** [comment]
Yes.  Migrate is a once-per-upgrade situation so you're right that a service probably isn't right.  I had hoped to eventually leverage [this strategy](https://engineering.instawork.com/elegant-database-migrations-on-ecs-74f3487da99f), but don't know if it's CloudFormation-friendly.

We use Celery (asynchronous task workers) with Django (python application framework).  Django is hosted on the asynchronous Daphne web server.  Here are the commands:

 - Daphne:  `daphne -u /code/pid/daphne_%(process_num)d.sock --fd 0 --proxy-headers <my_service>.asgi:application`
 - Celery:  `/usr/local/bin/celery worker --app=<my_service> --loglevel=WARNING`

We actually use the same image for each service's messaging interface as well.  There's very little shared code, but these workers are tightly coupled to changes in each service's API interface.  Workers are written in Twisted, an asynchronous Python framework with its own execution framework (i.e. `twistd`).  So we also run from this image commands like:

 - `twistd -n -y /code/<service name>/server/src/<worker name>.tac -l - --pidfile=<worker name>.pid`

In case it isn't obvious, `/code/` is where we `ADD` all our custom code in our Dockerfiles.

**Comment by ambsw-technology** [comment]
Perhaps also worth clarifying... Daphne's `.sock` binding leverages supervisor's `fcgi-program` feature.  If we weren't running in supervisor, it would be more like `daphne -b 0.0.0.0 -p 80 <my_service>.asgi:application`.

**Comment by michaelwittig** [comment]
I have no experience with the frameworks you use.

If all you need is to override the docker `CMD` you can edit the TaskDefinition here https://github.com/cfn-modules/fargate-service/blob/master/module.yml#L476 and open a PR.

**Comment by ambsw-technology** [comment]
I've discovered that I need a bunch of features that aren't in `cfn-modules` yet so I'm going to use (and contribute to) `aws-cf-templates`.  Exposing `command` is still a good idea here, but I'm going to close the issue since there's no obvious reason to prioritize this improvement over others.
