### ISSUE TITLE
Add Support for Service Discovery

### ISSUE THREAD

**Issue by ambsw-technology** [cfn-modules/fargate-service#18]
Does `cfn-modules` have a preferred way to populate a private DNS with ECS services?

Per [this article](https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-ecs-service-discovery/), it looks like the built-in ECS Service Discovery is normally implemented using (at least) the following:

 - `AWS::ServiceDiscovery::PrivateDnsNamespace`
 - `AWS::ServiceDiscovery::Service `
 - A `ServiceRegistries` entry under the `AWS::ECS::Service`

Obviously, no `ServiceRegistries` binding exists in this repo.   Further [the documentation on `PrivateDnsNamespace`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-servicediscovery-privatednsnamespace.html) states that:

> When you create a private DNS namespace, AWS Cloud Map automatically creates an Amazon Route 53 private hosted zone that has the same name as the namespace.

It seems like this is redundant to the Route 53 Private Zone that is created by `cfn-modules/route53-hosted-zone-private`.  I don't see an obvious way to link the one to the other -- unless the exact same name would cause the `PrivateDnsNamespace` to link to the `HostedZone`.

Coming from the other direction, some of the `aws-cf-templates` (e.g. [`elasticache-redis`](https://github.com/widdix/aws-cf-templates/blob/master/state/elasticache-redis.yaml)) do build a `AWS::Route53::RecordSet`, but these point to `ResourceRecords` like IP addresses.  If an `AWS::ECS::Service` exposes an IP address, it's not exported by the `fargate-service` package for use in an a `RecordSet` definition.

**Comment by michaelwittig** [comment]
We don't have support for CloudMap in cfn-modules at the moment. You can checkout https://github.com/widdix/aws-cf-templates/tree/master/fargate where you can find a cloudmap template.

**Comment by ambsw-technology** [comment]
Thanks.  I asked the pure-CF question on SO and have been told that [`ServiceDiscovery` and `HostedZone` don't play nice together](https://stackoverflow.com/a/58215718/1978687).  Unless they're wrong, I will need to modify `cfn-modules/rds-postgres` (or `aws-cf-templates/state/rds-postgres.yaml`) to integrate it with the `ServiceDiscovery` in `aws-cf-templates/fargate/service-cloudmap`.

Is the approach suggested in the [SO answer](https://stackoverflow.com/a/58215718) (i.e. using a `ServiceDiscovery::Instance` for postgres) the approach you prefer?  If so, I'm happy to submit a PR to (at least) `aws-cf-templates/state/rds-postgres.yaml`.  I would offer to PR `cfn-modules/rds-postgres` as well, but doubt I could write an appropriate test.

**Comment by michaelwittig** [comment]
`AWS::ServiceDiscovery::Service` / `AWS::ServiceDiscovery::Instance` seems valid. I'm don't understand why you want to add RDS. RDS has it's own CNAME which you could also use?
If you create CNAME (managed by Service Discovery) -> CNAME (managed by RDS) -> RDS Instance you will run into issued if you try to connect to your database in an encrypted way (the cert is only valid for the CNAME managed by RDS)

**Comment by ambsw-technology** [comment]
In Docker Swarm, I refer to my database container as simply `db` so that's what's in Parameter Store as the database hostname for my clients.  If I expose the database at the same alias on CF, I can point both environments to the same configurations during the migration.  In theory, it also makes it easier to migrate in the future.  For example, I could deploy an Aurora database, migrate my data, and all I need to do is change the CloudMap entry.  I don't need to reconfigure and redeploy my containers for the new CNAME.

**Comment by ambsw-technology** [comment]
The certificate mismatch didn't occur to me so I'll have to figure out if that's fatal.

**Comment by ambsw-technology** [comment]
Wondered if I could provide my own SSL certificate to AWS RDS and use `db.<mydomain>.com` (which swarm also supports).  Unfortunately, [RDS does not support custom certificates](https://forums.aws.amazon.com/thread.jspa?threadID=215902) and that response is 2-weeks old so it probably hasn't changed.

**Comment by ambsw-technology** [comment]
I'm going to close this.  I agree that it doesn't make sense to include a feature that interferes with the SSL connections.  If/when AWS makes architecture changes that make the two compatible, I can revisit.

**Comment by ambsw-technology** [comment]
It also looks like CloudMap names must use the format `<name>.<namespace>` so I can't even expose my services at `db` and/or `redis` (which is the legacy hostname).  For migration purposes, `db.local` and `redis.local` may work, but this makes it even harder to standardize hostnames in Swarm and ECS.
